{"name": "A. Aziz Surveyors Inc.", "phone": "905-237-8224", "city": "Richmond Hill", "province": "ON", "country": "CANADA", "unit_number": "#31", "street_name": "Newkirk Rd.,", "street_number": "120", "postal_code": "L4C 9S7"}
{"name": "Adam Kasprzak Surveying Ltd.", "phone": "613-432-3048", "city": "Renfrew", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Bridge St., PO Box 633", "street_number": "29", "postal_code": "K7V 4E7"}
{"name": "Acculine Inc.", "phone": "416-251-8490", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Kipling Avenue", "street_number": "661", "postal_code": "M8Z 5G2"}
{"name": "Annis O'Sullivan Vollebekk Ltd.", "phone": "613-443-3364", "city": "Embrun", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "P.O. Box , Rue Industriel", "street_number": "579", "postal_code": "K0A 1W0"}
{"name": "Alex Marton Ltd.", "phone": "905-879-9889", "city": "Concord", "province": "ON", "country": "CANADA", "unit_number": "8", "street_name": "Applewood Crescent,", "street_number": "160", "postal_code": "L4K 4H2"}
{"name": "Altimap Land Surveyors Inc.", "phone": "416-990-3001", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "212", "street_name": "Finch Avenue West,", "street_number": "222", "postal_code": "M2R 1M6"}
{"name": "AECON Geomatics Limited", "phone": "416-459-3002", "city": "Barrie", "province": "ON", "country": "CANADA", "unit_number": "D", "street_name": "Bayview Drive,", "street_number": "761", "postal_code": "L4N 9A5"}
{"name": "Aksan Piller Corporation Ltd.", "phone": "416-488-1174", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Mount Pleasant Road", "street_number": "943", "postal_code": "M4P 2L7"}
{"name": "AK & M Surveying Limited", "phone": "647-914-3361", "city": "Brampton", "province": "Ontario", "country": "Canada", "unit_number": "", "street_name": "Great Plains Street", "street_number": "15", "postal_code": "L6R 1Z6"}
{"name": "Adam Kasprzak Surveying Ltd.", "phone": "613-735-0764", "city": "Pembroke", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "PO Box  (432 Pembroke St. W.)", "street_number": "492", "postal_code": "K7V 4E7"}
{"name": "A.T. McLaren Limited", "phone": "905-527-8559", "city": "Hamilton", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "John Str. South, Suite 230", "street_number": "69", "postal_code": "L8N 2B9"}
{"name": "A.J. Clarke and Associates Ltd.", "phone": "905-528-8761", "city": "Hamilton", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Main St. West, Suite 300", "street_number": "25", "postal_code": "L8P 1H1"}
{"name": "Biason Surveying Inc.", "phone": "905-857-0541", "city": "Bolton", "province": "ON", "country": "CANADA", "unit_number": "9", "street_name": "Marconi Court,", "street_number": "2", "postal_code": "L7E 1E5"}
{"name": "Becker & Starcevic Ltd.", "phone": "416-745-9442", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Islington Avenue, Suite 205", "street_number": "2978", "postal_code": "M9L 2K6"}
{"name": "Barich Grenkie Surveying Ltd. (A division of Geomaple Canada Inc.)", "phone": "416-444-1100", "city": "Thornhill", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Essex Ave.", "street_number": "32", "postal_code": "L8G 1E5"}
{"name": "Barich Grenkie Surveying Ltd. (A division of Geomaple Canada Inc.)", "phone": "905-662-6767", "city": "Stoney Creek", "province": "ON", "country": "CANADA", "unit_number": "101", "street_name": "Highway 8,", "street_number": "297", "postal_code": "L8G 1E5"}
{"name": "Zubek, Emo, Patten & Thomsen Ltd.", "phone": "705-445-4910", "city": "Collingwood", "province": "ON", "country": "CANADA", "unit_number": "4", "street_name": "Mountain Road,", "street_number": "200", "postal_code": "L9Y 4V5"}
{"name": "Young & Young Surveying Inc. (a subsidiary of Mauro Group Inc.)", "phone": "905-951-6000", "city": "Bolton", "province": "ON", "country": "CANADA", "unit_number": "5", "street_name": "Holland Drive,", "street_number": "2", "postal_code": "L4K 0C3"}
{"name": "Young & Young Surveying Inc. (A Subsidiary of Mauro Group Inc.) ", "phone": "905-482-4668", "city": "Vaughan", "province": "ON", "country": "CANADA", "unit_number": "100", "street_name": "Applewood Crescent,", "street_number": "400", "postal_code": "L4K 0C3"}
{"name": "Young & Young Surveying (Etobicoke 2006) Inc.", "phone": "416-621-2676", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "North Queen Street, Suite 102", "street_number": "310", "postal_code": "M9C 5K4"}
{"name": "Wilson-Ford Surveying & Engineering Ltd.", "phone": "519-323-2451", "city": "Mount Forest", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "POB , 120 King Street East", "street_number": "294", "postal_code": "N0G 2L0"}
{"name": "West & Ruuska Ltd.", "phone": "519-752-8641", "city": "Brantford", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Nelson Street", "street_number": "17", "postal_code": "N3T 2M6"}
{"name": "Watson Land Surveyors Ltd.", "phone": "613-962-9521", "city": "Belleville", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Church Street", "street_number": "218", "postal_code": "K8N 3C3"}
{"name": "W.J. Simpson Surveying Ltd.", "phone": "613-756-1874", "city": "Barry's Bay", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "P.O. Box , 76 Zilney St.", "street_number": "827", "postal_code": "K0J 1B0"}
{"name": "W.J. Johnston Surveying Ltd.", "phone": "613-774-2414", "city": "Winchester", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "POB ,  12050 Main Street West", "street_number": "394", "postal_code": "K0C 2K0"}
{"name": "Vladimir Dosen Surveying", "phone": "416-466-0440", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Davisville Avenue", "street_number": "555", "postal_code": "M4S 1J2"}
{"name": "Verhaegen Land Surveyors, a Division of J.D. Barnes Limited", "phone": "519-258-1772", "city": "Windsor", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Ottawa Street", "street_number": "944", "postal_code": "N8H 1L8"}
{"name": "Verhaegen Land Surveyors, a Division of J.D. Barnes Limited", "phone": "519-322-2375", "city": "Leamington", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Talbot Street East", "street_number": "187", "postal_code": "N8H 1L8"}
{"name": "Van Harten Surveying Inc.", "phone": "519-940-4110", "city": "Orangeville", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Riddell Road", "street_number": "660", "postal_code": "N2L 5C6"}
{"name": "Van Harten Surveying Inc.", "phone": "519-821-2763", "city": "Guelph", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Woolwich Street", "street_number": "423", "postal_code": "N2L 5C6"}
{"name": "Vallee & Yeo Limited", "phone": "519-426-6270", "city": "Simcoe", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Talbot Street North", "street_number": "2", "postal_code": "N3Y 3W4"}
{"name": "Tulloch Mapping Solutions", "phone": "613-721-1138", "city": "Ottawa", "province": "Ontario", "country": "Canada", "unit_number": "", "street_name": "Morrison Drive, Suite 208", "street_number": "900", "postal_code": "K2H 8K7"}
{"name": "Tulloch Geomatics Inc.", "phone": "705-869-5792", "city": "Espanola", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Second Avenue", "street_number": "449", "postal_code": "P7B 6A7"}
{"name": "Tulloch Geomatics Inc.", "phone": "905-481-1678", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Atlantic Ave., Suite 438", "street_number": "80", "postal_code": "P7B 6A7"}
{"name": "Tulloch Geomatics Inc.", "phone": "", "city": "Timmins", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "River Park Road, Suite 402", "street_number": "690", "postal_code": ""}
{"name": "Tulloch Geomatics Inc.", "phone": "705-848-9175", "city": "Elliot Lake", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "- 12 Brunswick Walk", "street_number": "10", "postal_code": "P7B 6A7"}
{"name": "Tulloch Geomatics Inc.", "phone": "705-746-8404", "city": "Parry Sound", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Seguin Street", "street_number": "5", "postal_code": "P7B 6A7"}
{"name": "Tulloch Geomatics Inc.", "phone": "705-949-1457", "city": "Sault Ste. Marie", "province": "ON", "country": "CANADA", "unit_number": "8", "street_name": "Black Road,", "street_number": "71", "postal_code": "P7B 6A7"}
{"name": "Tulloch Geomatics Inc.", "phone": "705-789-7851", "city": "Huntsville", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Main Street West", "street_number": "80", "postal_code": "P7B 6A7"}
{"name": "Tulloch Geomatics Inc.", "phone": "705-671-2295", "city": "Sudbury", "province": "ON", "country": "CANADA", "unit_number": "L", "street_name": "Regent St.,", "street_number": "1942", "postal_code": "P7B 6A7"}
{"name": "Tulloch Geomatics Inc.", "phone": "807-333-8404", "city": "Thunder Bay", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "- 91 Cumberland St. S.,", "street_number": "102", "postal_code": "P7B 6A7"}
{"name": "Total Tech Surveying Inc.", "phone": "519-776-9887", "city": "Essex", "province": "ON", "country": "CANADA", "unit_number": "2 & 3", "street_name": "Talbot St. N.,", "street_number": "341", "postal_code": "N8M 2W3"}
{"name": "Topotec Inc.", "phone": "416-219-9956", "city": "Markham", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Steeles Ave. East", "street_number": "108", "postal_code": "L3T 1A4"}
{"name": "Tham Surveying Limited", "phone": "905-761-6521", "city": "Vaughan", "province": "ON", "country": "CANADA", "unit_number": "7", "street_name": "Keele Street,", "street_number": "8888", "postal_code": "L4K 2N2"}
{"name": "Ted Van Lankveld, O.L.S.", "phone": "905-792-6641", "city": "Brampton", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Goldcrest Road", "street_number": "110", "postal_code": "L6S 1H4"}
{"name": "TBT Surveyors Inc.", "phone": "807-624-5160", "city": "Thunder Bay", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Yonge St.", "street_number": "1918", "postal_code": "P7E 6T9"}
{"name": "Tarasick McMillan Kubicki Limited", "phone": "905-569-8849", "city": "Mississauga", "province": "ON", "country": "CANADA", "unit_number": "42", "street_name": "Sladeview Cres.,", "street_number": "4181", "postal_code": "L5L 5R2"}
{"name": "T.A. Bunker Surveying Ltd.", "phone": "705-687-5883", "city": "Gravenhurst", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "POB ,  150 John Street North", "street_number": "1180", "postal_code": "P1P 1V4"}
{"name": "Sylvester & Brown (A Division of Donevan Fleischmann Petrich Ltd.)", "phone": "905-885-2260", "city": "Port Hope", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Toronto Road", "street_number": "191", "postal_code": "L1A 2Z3"}
{"name": "Swift Surveys Limited", "phone": "416-436-6862", "city": "Toronto", "province": "Ontario", "country": "Canada", "unit_number": "", "street_name": "Spadina Ave.", "street_number": "671", "postal_code": "M5S 2H9"}
{"name": "Surveyors On Site Inc.", "phone": "705-665-6340", "city": "Sudbury", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Bancroft Drive", "street_number": "1623", "postal_code": "N8W 3R8"}
{"name": "Surveyors On Site Inc.", "phone": "705-622-0872", "city": "New Liskeard", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Wellington Street, PO Box 1599", "street_number": "17", "postal_code": "N8W 3R8"}
{"name": "Surveyors On Site Inc.", "phone": "519-890-4219", "city": "Windsor", "province": "ON", "country": "CANADA", "unit_number": "3", "street_name": "Walker Road,", "street_number": "3244", "postal_code": "N8W 3R8"}
{"name": "Surveying Specialist Canada Inc.", "phone": "647-570-2998", "city": "Brampton", "province": "Ontario", "country": "Canada", "unit_number": "", "street_name": "McLaughlin Road North", "street_number": "9720", "postal_code": "L6X 0T8"}
{"name": "Suda & Maleszyk Surveying Inc.", "phone": "905-732-7651", "city": "Welland", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "East Main Str., Suite 2", "street_number": "26", "postal_code": "L3B 3W3"}
{"name": "Stojanovic Land Surveying", "phone": "416-781-4991", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Bathurst Street, Suite 104", "street_number": "2953", "postal_code": "M6A 3B2"}
{"name": "Stantec Geomatics Ltd.", "phone": "807-285-9008", "city": "Thunder Bay", "province": "Ontario", "country": "Canada", "unit_number": "", "street_name": "Innovation Drive", "street_number": "1263", "postal_code": "K2C 3G4"}
{"name": "Stantec Geomatics Ltd.", "phone": "519-645-2007", "city": "London", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "- 171 Queens Avenue", "street_number": "600", "postal_code": "K2C 3G4"}
{"name": "Stantec Geomatics Ltd.", "phone": "519-585-7264", "city": "Waterloo", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "-300 Hagey Boulevard", "street_number": "100", "postal_code": "K2C 3G4"}
{"name": "Stantec Geomatics Ltd.", "phone": "613-722-4420", "city": "Ottawa", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Clyde Avenue, Suite 400", "street_number": "1331", "postal_code": "K2C 3G4"}
{"name": "Sperling Surveying Inc.", "phone": "905-954-5553", "city": "Minden", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Gelert Road, PO Box 254", "street_number": "1337", "postal_code": "K0M 2K0"}
{"name": "Speight, van Nostrand & Gibson Limited", "phone": "416-749-7864", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "s 65 & 66", "street_name": "Oakdale Rd.,", "street_number": "750", "postal_code": "M3N 2Z4"}
{"name": "South Western Surveying Ltd.", "phone": "226-377-8071", "city": "Port Stanley", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Harrison Place", "street_number": "147", "postal_code": "N5L 1A1"}
{"name": "SEA Graphics Inc.", "phone": "905-940-2114", "city": "Markham", "province": "Ontario", "country": "Canada", "unit_number": "", "street_name": "- 3980 14th Avenue", "street_number": "16", "postal_code": "L3R 0B1"}
{"name": "Schaeffer Dzaldov Bennett Ltd.", "phone": "416-987-0101", "city": "Concord", "province": "ON", "country": "CANADA", "unit_number": "1", "street_name": "Jardin Drive,", "street_number": "64", "postal_code": "L3Y 8Z1"}
{"name": "SBM Geomatics Ltd.", "phone": "519-471-6667", "city": "London", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Adelaide Street North, Suite 301", "street_number": "1599", "postal_code": "N5X 4E8"}
{"name": "Sani International Technology Advisors Inc.", "phone": "905-943-7774", "city": "Markham", "province": "Ontario", "country": "Canada", "unit_number": "", "street_name": "14th Ave., Suite 224", "street_number": "3075", "postal_code": "L3R 0G9"}
{"name": "Rugged Geomatics Inc.", "phone": "807-468-8516", "city": "Kenora", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Main Street South", "street_number": "138", "postal_code": "P9N 1S9"}
{"name": "Rudy Mak Surveying Ltd.", "phone": "705-722-3845", "city": "Port Severn", "province": "Ontario", "country": "Canada", "unit_number": "", "street_name": "Port Severn Road North", "street_number": "32", "postal_code": "L4N 8M5"}
{"name": "Rudy Mak Surveying Ltd.", "phone": "705-722-3845", "city": "Barrie", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Big Bay Point Road", "street_number": "89", "postal_code": "L4N 8M5"}
{"name": "RS Surveying Limited", "phone": "905-554-1021", "city": "Stouffville", "province": "Ontario", "country": "Canada", "unit_number": "9", "street_name": "Ringwood Drive,", "street_number": "117", "postal_code": "L4A 8C1"}
{"name": "R-PE Surveying Ltd.", "phone": "416-635-5000", "city": "Woodbridge", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Chrislea Road, Suite 7", "street_number": "643", "postal_code": "L4L 8A3"}
{"name": "Rouse Surveyors Inc.", "phone": "416-598-3933", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Fort York Blvd.", "street_number": "56", "postal_code": "M5V 4A6"}
{"name": "Ronald J. Stewart, O.L.S.", "phone": "647-222-1249", "city": "Alliston", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Tottenham Road", "street_number": "3756", "postal_code": "L9R 1V4"}
{"name": "Rodney Geyer, Ontario Land Surveyor Inc.", "phone": "705-434-0411", "city": "Alliston", "province": "ON", "country": "CANADA", "unit_number": "29", "street_name": "Parsons Road,", "street_number": "180", "postal_code": "L9R 1E8"}
{"name": "Rodney G. Reynolds, O.L.S.", "phone": "705-429-5028", "city": "Wasaga Beach", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "P.O. Box", "street_number": "333", "postal_code": "L9Z 1A4"}
{"name": "Robert M. McDermott Surveying Limited", "phone": "705-385-3198", "city": "Port Sydney", "province": "ON", "country": "CANADA", "unit_number": "4 - 15 South Mary Lake Road", "street_name": "", "street_number": "", "postal_code": "P0B 1L0"}
{"name": "Richard Larocque Ltd.", "phone": "905-688-1413", "city": "St. Catharines", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Lyman Street", "street_number": "12", "postal_code": "L2R 5M7"}
{"name": "Rasch & Hyde Limited", "phone": "905-871-9757", "city": "Fort Erie", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "POB ,  74 Jarvis Street", "street_number": "550", "postal_code": "N1A 2X1"}
{"name": "Rasch & Hyde Limited", "phone": "905-774-7188", "city": "Dunnville", "province": "ON", "country": "CANADA", "unit_number": "B", "street_name": "POB ,  1333 Highway No. 3 East", "street_number": "6", "postal_code": "N1A 2X1"}
{"name": "Raikes Geomatics Inc.", "phone": "705-526-7552", "city": "Midland", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Elizabeth Street", "street_number": "529", "postal_code": "L4N 9A1"}
{"name": "Raikes Geomatics Inc.", "phone": "705-722-6222", "city": "Barrie", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Welham Road, Suite 102", "street_number": "642", "postal_code": "L4N 9A1"}
{"name": "R.F. Dore Surveying Ltd.", "phone": "519-396-3464", "city": "Kincardine", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Queen Street, Box 571", "street_number": "932", "postal_code": "N2Z 2Y2"}
{"name": "R. Avis Surveying Inc.", "phone": "416-490-8352", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Yorkland Boulevard, Suite 203", "street_number": "235", "postal_code": "M2J 4Y8"}
{"name": "Protect Your Boundaries Inc.", "phone": "289-459-0210", "city": "Thornhill", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Centre Street, Suite 101", "street_number": "1137", "postal_code": "L4J 3M6"}
{"name": "Pearson and Pearson Limited", "phone": "416-845-2655", "city": "Vaughan", "province": "ON", "country": "CANADA", "unit_number": "B", "street_name": "Jane Street,", "street_number": "10933", "postal_code": "L6A 1S1"}
{"name": "Paul Wilson Consulting Ltd.", "phone": "705-286-3400", "city": "Minden", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "POB , 3 Newcastle Street", "street_number": "151", "postal_code": "K0M 2K0"}
{"name": "P.J. Williams, O.L.S.", "phone": "519-941-6231", "city": "Orangeville", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Sunset Drive", "street_number": "34", "postal_code": "L9W 2G9"}
{"name": "P.A. Miller Surveying Ltd.", "phone": "613-395-3070", "city": "Stirling", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Campbellford Rd., PO 520", "street_number": "18", "postal_code": "K0K 3E0"}
{"name": "P.A. Blackburn Limited", "phone": "705-476-2600", "city": "North Bay", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Lake Street", "street_number": "140", "postal_code": "P1B 4M8"}
{"name": "P. Salna Company Ltd.", "phone": "905-884-5275", "city": "Richmond Hill", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Industrial Road", "street_number": "64", "postal_code": "L4C 2Y1"}
{"name": "Omari Mwinyi Surveying Ltd.", "phone": "905-831-5485", "city": "Pickering", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Pinegrove Avenue", "street_number": "1905", "postal_code": "L1V 6T1"}
{"name": "Northway/Photomap/Remote Sensing Ltd.", "phone": "705-730-6694", "city": "Minesing", "province": "Ontario", "country": "Canada", "unit_number": "", "street_name": "P.O. Box , 2-1630 George Johnston Road", "street_number": "126", "postal_code": "L0L 1Y0"}
{"name": "Northern Link Survey Group [o/b 2307869 Ontario Limited]", "phone": "705-985-2610", "city": "Barrie", "province": "Ontario", "country": "Canada", "unit_number": "", "street_name": "", "street_number": "", "postal_code": ""}
{"name": "Nanfara & Ng Surveyors Inc.", "phone": "905-856-5923", "city": "Woodbridge", "province": "ON", "country": "CANADA", "unit_number": "9", "street_name": "Ashbridge Circle,", "street_number": "1", "postal_code": "L4L 3R5"}
{"name": "NA Geomatics Inc. (formerly Benedict Raithby Inc.)", "phone": "519-537-6212", "city": "Woodstock", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Dundas Street", "street_number": "871", "postal_code": "N4S 1G8"}
{"name": "NA Geomatics Inc.", "phone": "519-273-3205", "city": "Stratford", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Erie St. Suite 2", "street_number": "107", "postal_code": "N5A 2M5"}
{"name": "MTE Ontario Land Surveyors Ltd.", "phone": "519-672-4551", "city": "London", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "St. George St.,", "street_number": "123", "postal_code": "N5A 2A5"}
{"name": "MTE Ontario Land Surveyors Ltd.", "phone": "905-639-2552", "city": "Burlington", "province": "ON", "country": "CANADA", "unit_number": "A", "street_name": "Sutton Drive,", "street_number": "1016", "postal_code": "N5A 2A5"}
{"name": "MTE Ontario Land Surveyors Ltd.", "phone": "519-743-6500", "city": "Kitchener", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Bingemans Centre Dr.", "street_number": "520", "postal_code": "N5A 2A5"}
{"name": "MTE Ontario Land Surveyors Ltd.", "phone": "519-271-7952", "city": "Stratford", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Home Street", "street_number": "365", "postal_code": "N5A 2A5"}
{"name": "MRM Surveying Ltd.", "phone": "905-833-0332", "city": "King City", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Keele St.", "street_number": "12865", "postal_code": "L7B 1H7"}
{"name": "Monteith & Sutherland Ltd.", "phone": "519-542-4300", "city": "Sarnia", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Upper Canada Drive", "street_number": "801", "postal_code": "N7W 1A3"}
{"name": "Miller & Urso Surveying Inc.", "phone": "705-474-1210", "city": "North Bay", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Seymour Street", "street_number": "1501", "postal_code": "P1A 0C5"}
{"name": "Metz & Lorentz Limited (a division of Van Harten Surveying Inc.)", "phone": "519-742-8371", "city": "Waterloo", "province": "ON", "country": "CANADA", "unit_number": "7", "street_name": "Weber Street North,", "street_number": "572", "postal_code": "N2L 5C6"}
{"name": "Meldrum-Jason Surveyors, A Division of Ivan B. Wallace, O.L.S. Ltd.", "phone": "613-925-0575", "city": "Prescott", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "P.O. Box , Suite 205 - 197 Water Street", "street_number": "790", "postal_code": "K0C 1P0"}
{"name": "Meldrum-Jason Surveyors, A Division of Ivan B. Wallace, O.L.S. Ltd.", "phone": "613-932-8124", "city": "Long Sault", "province": "ON", "country": "CANADA", "unit_number": "4", "street_name": "Cornwall Centre Road,", "street_number": "17171", "postal_code": "K0C 1P0"}
{"name": "McKechnie Surveying Ltd.", "phone": "519-578-5570", "city": "Kitchener", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "McIntyre Dr.", "street_number": "85", "postal_code": "N2R 1H6"}
{"name": "McIntosh Perry Surveying Inc.", "phone": "613-267-6524", "city": "Perth", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Drummond Concession 5-A, R.R. #7", "street_number": "3240", "postal_code": "K7H 3C9"}
{"name": "Matthews Cameron Heywood, A Division of J.D. Barnes Limited", "phone": "905-358-3693", "city": "Niagara Falls", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "- 4318 Portage Road", "street_number": "2", "postal_code": "L2E 6A4"}
{"name": "Martin W. Knisley, O.L.S.", "phone": "705-444-6203", "city": "Duntroon", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "P.O. Box", "street_number": "48", "postal_code": "L0M 1H0"}
{"name": "Mandarin Surveyors Limited", "phone": "647-430-1366", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "121", "street_name": "Midland Avenue,", "street_number": "2400", "postal_code": "M1S 1X7"}
{"name": "MacKay, MacKay & Peters Limited", "phone": "905-639-1375", "city": "Burlington", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "South Service Road, Suite 101", "street_number": "3380", "postal_code": "L7N 3J5"}
{"name": "MacAulay, White & Muir Ltd.", "phone": "519-752-0040", "city": "Brantford", "province": "ON", "country": "CANADA", "unit_number": "2", "street_name": "Hardy Road,", "street_number": "440", "postal_code": "N3T 5L8"}
{"name": "Lloyd & Purcell Ltd. (a division of Schaeffer Dzaldov Bennett Ltd.)", "phone": "905-895-6416", "city": "Newmarket", "province": "ON", "country": "CANADA", "unit_number": "28", "street_name": "Gorham Street,", "street_number": "1228", "postal_code": "L3Y 8Z1"}
{"name": "Lejan Land Surveying Inc.", "phone": "905-643-6131", "city": "Stoney Creek", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Barton Street East", "street_number": "572", "postal_code": "L8E 4V2"}
{"name": "Lanthier & Gilmore Surveying Ltd.", "phone": "905-835-5477", "city": "Port Colborne", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Clarence Street", "street_number": "173", "postal_code": "L3K 3G4"}
{"name": "Land Survey Group Inc.", "phone": "416-252-2511", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "1", "street_name": "The Queensway,", "street_number": "777", "postal_code": "M8Z 1N4"}
{"name": "L.U. Maughan Company Limited", "phone": "705-746-5805", "city": "Parry Sound", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "McMurray Street", "street_number": "5", "postal_code": "P2A 1E6"}
{"name": "Krcmar Surveyors Ltd.", "phone": "905-738-0053", "city": "Thornhill", "province": "ON", "country": "CANADA", "unit_number": "101 - 1137 Centre Street", "street_name": "", "street_number": "", "postal_code": "L4J 3M6"}
{"name": "Kirkup Mascoe Ure Surveying, A Division of J.D. Barnes Limited", "phone": "905-685-5931", "city": "St. Catharines", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Eastchester Avenue", "street_number": "49", "postal_code": "L2P 2Y6"}
{"name": "Kim Husted Surveying Ltd.", "phone": "519-842-3638", "city": "Tillsonburg", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Harvey Street", "street_number": "30", "postal_code": "N3Y 4J9"}
{"name": "Keatley Surveying Ltd.", "phone": "705-368-2221", "city": "Little Current", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "POB ,  39 Water Street, East", "street_number": "578", "postal_code": "P0P 1K0"}
{"name": "Kad Lanka Surveying Inc.", "phone": "647-267-4322", "city": "Brampton", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Ezra Crescent", "street_number": "34", "postal_code": "L7A 5A6"}
{"name": "K.L. Stidwill (A Division of 1448413 Ontario Inc.)", "phone": "613-932-7424", "city": "Cornwall", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Sydney Street", "street_number": "107", "postal_code": "K6H 3H1"}
{"name": "K. Adams Surveying Ltd.", "phone": "613-537-9898", "city": "Ingleside", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "POB , 15 Dickinson Dr.", "street_number": "149", "postal_code": "K0C 1M0"}
{"name": "Jordan Bennett Geomatics Inc.", "phone": "613-342-7525", "city": "Brockville", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "P.O. Box ,  33 Perth Street", "street_number": "485", "postal_code": "K6V 5V7"}
{"name": "John E. Jackson Surveying Ltd.", "phone": "705-789-8283", "city": "Huntsville", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Main Street West, Suite 101", "street_number": "9", "postal_code": "P1H 2C5"}
{"name": "Jewitt and Dixon Ltd. (A Division of Kim Husted Surveying Ltd.)", "phone": "519-426-0842", "city": "Simcoe", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "R.R. , 5 Park Road", "street_number": "1", "postal_code": "N3Y 4J9"}
{"name": "JBF Surveyors", "phone": "705-652-6198", "city": "Lakefield", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "POB  (44 Clementi Street)", "street_number": "70", "postal_code": "K0L 2H0"}
{"name": "James E. Kirkland Ltd.", "phone": "705-523-1900", "city": "Sudbury", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Desloges Road", "street_number": "2651", "postal_code": "P3G 1C5"}
{"name": "J.R. Finnie, O.L.S.", "phone": "519-833-2380", "city": "Erin", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Eighth Line, Box 31", "street_number": "5411", "postal_code": "N0B 1T0"}
{"name": "J.H. Gelbloom Surveying Limited", "phone": "905-338-8210", "city": "Oakville", "province": "ON", "country": "CANADA", "unit_number": "102", "street_name": "Morden Road,", "street_number": "476", "postal_code": "L6K 3W4"}
{"name": "J.D. Barnes Limited", "phone": "519-621-9600", "city": "Kitchener", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "King Street East, Suite 100", "street_number": "4273", "postal_code": ""}
{"name": "J.D. Barnes Limited", "phone": "416-368-3737", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Richmond St. East, Suite 107", "street_number": "411", "postal_code": "N1H 8J1"}
{"name": "J.D. Barnes Limited", "phone": "905-477-3600", "city": "Markham", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Renfrew Dr., Suite 100", "street_number": "140", "postal_code": "N1H 8J1"}
{"name": "J.D. Barnes Limited", "phone": "613-731-7244", "city": "Ottawa", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Steacie Drive, Suite 103", "street_number": "62", "postal_code": "N1H 8J1"}
{"name": "J.D. Barnes Limited", "phone": "807-622-6277", "city": "Thunder Bay", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Russell Street", "street_number": "1158", "postal_code": "N1H 8J1"}
{"name": "J.D. Barnes Limited", "phone": "905-723-1212", "city": "Whitby", "province": "ON", "country": "CANADA", "unit_number": "38", "street_name": "Scotia Court,", "street_number": "110", "postal_code": "N1H 8J1"}
{"name": "J.D. Barnes Limited", "phone": "905-875-9955", "city": "Milton", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Wheelabrator Way, Suite A", "street_number": "401", "postal_code": "N1H 8J1"}
{"name": "J.D. Barnes Limited", "phone": "705-739-6770", "city": "Barrie", "province": "ON", "country": "CANADA", "unit_number": "V", "street_name": "Commerce Park Dr.,", "street_number": "142", "postal_code": "N1H 8J1"}
{"name": "J. Halsall, O.L.S. / J. Halsall Hydrographic Surveys", "phone": "905-737-6986", "city": "Richmond Hill", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Centre Street West", "street_number": "119", "postal_code": "L4C 3P6"}
{"name": "J. Don MacMillan Limited", "phone": "519-291-1313", "city": "Listowel", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Davidson Avenue South", "street_number": "144", "postal_code": "N4W 2J6"}
{"name": "J. Anne Cole Surveying Ltd.", "phone": "705-561-7897", "city": "Sudbury", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Ramsey Lake Road", "street_number": "718", "postal_code": "P3E 6H5"}
{"name": "Izaak de Rijcke Surveying Inc.", "phone": "519-837-2551", "city": "Guelph", "province": "ON", "country": "CANADA", "unit_number": "122", "street_name": "Elmira Road North,", "street_number": "355", "postal_code": "N1K 1S5"}
{"name": "Ivan B. Wallace Ontario Land Surveyor Ltd.", "phone": "905-465-9944", "city": "Oakville", "province": "Ontario", "country": "Canada", "unit_number": "6", "street_name": "North Service Road,", "street_number": "1075", "postal_code": "L1C 4N4"}
{"name": "Ivan B. Wallace Ontario Land Surveyor Ltd.", "phone": "613-389-3344", "city": "Kingston", "province": "ON", "country": "CANADA", "unit_number": "1", "street_name": "Norris Court,", "street_number": "637", "postal_code": "L1C 4N4"}
{"name": "Ivan B. Wallace Ontario Land Surveyor Ltd.", "phone": "905-623-2205", "city": "Bowmanville", "province": "ON", "country": "CANADA", "unit_number": "16, Box 2", "street_name": "Mearns Court,", "street_number": "71", "postal_code": "L1C 4N4"}
{"name": "Ivan B. Wallace Ontario Land Surveyor Ltd", "phone": "613-966-9898", "city": "Belleville", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Highway 62 South, Prince Edward Square", "street_number": "5503", "postal_code": "K8N 4Z7"}
{"name": "IN Engineering & Surveying", "phone": "613-342-2611", "city": "Brockville", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "King Street East, Suite 205", "street_number": "51", "postal_code": "K6V 5V2"}
{"name": "Hunt Surveys Inc.", "phone": "905-764-8759", "city": "Richmond Hill", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "-A West Wilmot Str., # 207", "street_number": "45", "postal_code": "L4B 2P2"}
{"name": "Hopkins Chitty Land Surveyors Inc.", "phone": "613-354-5420", "city": "Napanee", "province": "ON", "country": "CANADA", "unit_number": "3", "street_name": "Advance Avenue,", "street_number": "401", "postal_code": "K7P 0G2"}
{"name": "Hopkins Chitty Land Surveyors Inc.", "phone": "613-384-9266", "city": "Kingston", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Gardiners Road Suite 102", "street_number": "1224", "postal_code": "K7P 0G2"}
{"name": "Hook & Todgham Surveying Inc.", "phone": "519-354-6122", "city": "Chatham", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "- 330 Richmond Street", "street_number": "103", "postal_code": "N7M 1P7"}
{"name": "Holding Jones Vanderveen Inc.", "phone": "905-660-4000", "city": "Vaughan", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Langstaff Rd., Suite 1002", "street_number": "1700", "postal_code": "L4K 3S3"}
{"name": "Hewett & Milne Ltd.", "phone": "519-376-5528", "city": "Owen Sound", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "POB ,  302 - 8th Street East", "street_number": "112", "postal_code": "N4K 5P1"}
{"name": "H.F. Grander Co. Ltd.", "phone": "905-985-3600", "city": "Port Perry", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "POB ,  1575 Hwy 7A West, U. 2A", "street_number": "616", "postal_code": "L9L 1A6"}
{"name": "H.A. Ken Shipman Surveying Ltd.", "phone": "613-489-3910", "city": "North Gower", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "POB , 6563 Fourth Line Rd (Main St)", "street_number": "53", "postal_code": "K0A 2T0"}
{"name": "Guido Papa Surveying (a division of J.D. Barnes Limited)", "phone": "905-264-2727", "city": "Vaughan", "province": "ON", "country": "CANADA", "unit_number": "B7 - 9135 Keele St.", "street_name": "", "street_number": "", "postal_code": "L4K 0J4"}
{"name": "Guenther Rueb Surveying Limited", "phone": "519-576-7310", "city": "Kitchener", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Irvin Street", "street_number": "18", "postal_code": "N2H 1K8"}
{"name": "Greg Bishop Surveying and Consulting Ltd.", "phone": "705-457-2811", "city": "Haliburton", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Mallard Road, P.O. Box 309", "street_number": "121", "postal_code": "K0M 1S0"}
{"name": "Greater Toronto Acres Surveying Inc.", "phone": "416-679-0572", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "12", "street_name": "Steeles Ave. West,", "street_number": "7003", "postal_code": "M9W 0A2"}
{"name": "Goodridge Goulet Planning and Surveying Ltd.", "phone": "705-493-7974", "city": "North Bay", "province": "ON", "country": "CANADA", "unit_number": "#1", "street_name": "Main Street East,", "street_number": "490", "postal_code": "P1B 1B5"}
{"name": "Gifford Harris Surveying Ltd.", "phone": "613-392-2177", "city": "Trenton", "province": "ON", "country": "CANADA", "unit_number": "1", "street_name": "Glen Miller Rd,", "street_number": "255", "postal_code": "K8V 5P8"}
{"name": "Gibson Surveying Inc.", "phone": "519-438-7794", "city": "London", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Winblest Ave.", "street_number": "517", "postal_code": "N6C 3C2"}
{"name": "GeoVerra (ON) Ltd.", "phone": "905-823-8500", "city": "Oakville", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Chartwell Road, Suite 300", "street_number": "610", "postal_code": "L3T 0A1"}
{"name": "GeoVerra (ON) Ltd.", "phone": "905-882-4211", "city": "Thornhill", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Commerce Valley Drive West", "street_number": "100", "postal_code": "L3T 0A1"}
{"name": "George Bracken Limited", "phone": "613-283-2233", "city": "Smiths Falls", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "POB ,  40 Main Street West", "street_number": "24", "postal_code": "K7A 4S9"}
{"name": "GEOPLAN Surveying Ltd.", "phone": "416-731-2717", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Wynford Drive, Suite 209", "street_number": "40", "postal_code": "M3C 1J5"}
{"name": "Genesis Land Surveying Inc.", "phone": "905-499-2956", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Four Seasons Place, th Floor", "street_number": "10", "postal_code": "M9B 6H7"}
{"name": "Fiddes Clipsham Inc.", "phone": "905-877-2211", "city": "Halton Hills", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Mountainview Road, Suite 101", "street_number": "16", "postal_code": "L7G 4K1"}
{"name": "Farley, Smith & Denis Surveying Ltd.", "phone": "613-727-8226", "city": "Ottawa", "province": "ON", "country": "CANADA", "unit_number": "10", "street_name": "Colonnade Rd. North,", "street_number": "190", "postal_code": "K2E 7J5"}
{"name": "Fairhall Moffatt & Woodland Limited", "phone": "613-591-2580", "city": "Kanata", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "- 600 Terry Fox Drive", "street_number": "100", "postal_code": "K2L 4B6"}
{"name": "F.S. Surveying Inc.", "phone": "416-786-8080", "city": "Toronto", "province": "", "country": "Canada", "unit_number": "", "street_name": "Colwick Drive", "street_number": "7", "postal_code": "M2K 2G2"}
{"name": "Ertl Surveyors", "phone": "905-731-7834", "city": "Richmond Hill", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "- 1234 Reid Street", "street_number": "10", "postal_code": "L4B 1C1"}
{"name": "Elliott and Parr (Peterborough) Ltd. (a wholly owned subsidiary of J.D. Barnes Ltd.)", "phone": "705-745-8444", "city": "Peterborough", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "POB ,  211 Sherbrooke Street", "street_number": "1116", "postal_code": "K9J 2N2"}
{"name": "E.W. Bowyer Inc.", "phone": "905-294-8093", "city": "Markham", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Markham Road, Suite 201A", "street_number": "9275", "postal_code": "L6E 1A3"}
{"name": "E.R. Garden Limited", "phone": "905-895-5600", "city": "Newmarket", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Journey's End Circle, # 1", "street_number": "1260", "postal_code": "L3Y 8Z7"}
{"name": "E.J. Williams Surveying Limited", "phone": "705-386-2291", "city": "South River", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "P.O. Box", "street_number": "10", "postal_code": "P1H 1C2"}
{"name": "E.J. Williams Surveying Limited", "phone": "705-789-4171", "city": "Huntsville", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "- 133 Highway # 0", "street_number": "6", "postal_code": "P1H 1C2"}
{"name": "Dorin Popa Surveying", "phone": "416-429-4165", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Gamble Ave., Apt. 306", "street_number": "20", "postal_code": "M4K 2G9"}
{"name": "Donevan Fleischmann Petrich Limited", "phone": "905-725-4795", "city": "Oshawa", "province": "ON", "country": "CANADA", "unit_number": "1", "street_name": "Boundary Road,", "street_number": "1101", "postal_code": "L1J 8P8"}
{"name": "Donald Roberts Surveying Ltd.", "phone": "416-755-5320", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Railside Road, Suite 304", "street_number": "111", "postal_code": "M3A 1B2"}
{"name": "Dinsmore & England Ltd.", "phone": "519-371-9420", "city": "Owen Sound", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "2nd Avenue West", "street_number": "870", "postal_code": "N4K 4M5"}
{"name": "Derek G. Graham Limited", "phone": "519-846-5533", "city": "Elora", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Colborne Street East, P.O. Box 2922", "street_number": "7669", "postal_code": "N0B 1S0"}
{"name": "Delph & Jenkins North Ltd.", "phone": "905-841-8526", "city": "Aurora", "province": "ON", "country": "CANADA", "unit_number": "6", "street_name": "Industrial Pkwy South,", "street_number": "220", "postal_code": "L4G 3V6"}
{"name": "Dearden and Stanton Limited", "phone": "705-325-9521", "city": "Orillia", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Coldwater Street East", "street_number": "89", "postal_code": "L3V 1W8"}
{"name": "David U. Maughan", "phone": "705-746-5588", "city": "Parry Sound", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Miller Street", "street_number": "9", "postal_code": "P2A 1S7"}
{"name": "David B. Searles Surveying Ltd.", "phone": "905-273-6840", "city": "Mississauga", "province": "ON", "country": "CANADA", "unit_number": "206", "street_name": "Sherwoodtowne Blvd.,", "street_number": "4255", "postal_code": "L4Z 1Y5"}
{"name": "D.S. Urso Surveying Ltd.", "phone": "705-759-9037", "city": "Sault Ste. Marie", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "-C Fourth Line East", "street_number": "536", "postal_code": "P6A 6J8"}
{"name": "D.S. Dorland Limited", "phone": "705-673-2556", "city": "Sudbury", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Larch Street", "street_number": "298", "postal_code": "P3B 1M1"}
{"name": "D. Culbert Ltd.", "phone": "519-524-5321", "city": "Goderich", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "North Street", "street_number": "50", "postal_code": "N7A 2T5"}
{"name": "Cunningham McConnell Limited", "phone": "905-845-3497", "city": "Oakville", "province": "ON", "country": "CANADA", "unit_number": "38", "street_name": "Speers Road,", "street_number": "1200", "postal_code": "L9T 1N7"}
{"name": "Cunningham McConnell Limited", "phone": "905-878-7810", "city": "Milton", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Main Street", "street_number": "205", "postal_code": "L9T 1N7"}
{"name": "Coote, Hiley, Jemmett Limited (a wholly owned subsidiary of SOS)", "phone": "800-494-1443", "city": "Bracebridge", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Keith Road", "street_number": "127", "postal_code": "P1L 0A1"}
{"name": "Coe Fisher Cameron Land Surveyors, A Division of J.D. Barnes Limited", "phone": "705-324-4152", "city": "Lindsay", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Commerce Place, Suite 201", "street_number": "3", "postal_code": "K9V 0N5"}
{"name": "Clarke Wilkinson Alton Surveying", "phone": "416-750-3018", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "-D Industrial Street, Suite 3", "street_number": "43", "postal_code": "M4G 1Z2"}
{"name": "Clancy & Hopkins Surveying Ltd.", "phone": "613-354-4221", "city": "Napanee", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "POB ,  42 Bridge Street East", "street_number": "3", "postal_code": "K7R 1J8"}
{"name": "Chapple, Galbraith Surveyors Ltd.", "phone": "705-765-3579", "city": "Port Carling", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Box , 2 Bailey Street", "street_number": "496", "postal_code": "P0B 1J0"}
{"name": "Chambers and Associates Surveying Ltd.", "phone": "905-735-7841", "city": "Welland", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Thorold Rd. East", "street_number": "12", "postal_code": "L3C 3T2"}
{"name": "Callon Dietz Incorporated Ontario Land Surveyors", "phone": "", "city": "Carleton Place", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Roe Steet", "street_number": "19", "postal_code": ""}
{"name": "Callon Dietz Incorporated Ontario Land Surveyors", "phone": "705-478-6699", "city": "North Bay", "province": "ON", "country": "CANADA", "unit_number": "10", "street_name": "Booth Road,", "street_number": "191", "postal_code": "P1A 4K3"}
{"name": "C.T. Strongman Surveying Ltd. (a Division of Dearden Stanton)", "phone": "705-329-0765", "city": "Orillia", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Coldwater Street East", "street_number": "86", "postal_code": "L3V 1W7"}
{"name": "C.A. MacDonald Surveying Inc.", "phone": "705-730-6893", "city": "Barrie", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Blake Street", "street_number": "204", "postal_code": "L4M 1K3"}
{"name": "C. Wahba Surveying Ltd.", "phone": "905-851-1300", "city": "Woodbridge", "province": "Ontarrio", "country": "Canada", "unit_number": "", "street_name": "Vaughan Valley Blvd.", "street_number": "285", "postal_code": "L4H 3B5"}
{"name": "Brooks & Muir Surveying (Div. of Macaulay White & Muir Ltd.)", "phone": "519-539-8089", "city": "Woodstock", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Princess Street, Suite 120", "street_number": "514", "postal_code": "N4S 4G9"}
{"name": "Bowers Jones Fournier Surveying Ltd.", "phone": "705-726-6201", "city": "Barrie", "province": "ON", "country": "CANADA", "unit_number": "N,", "street_name": "Bryne Dr.,", "street_number": "570", "postal_code": "L4N 9P6"}
{"name": "Bortolussi Surveying Ltd.", "phone": "705-675-2566", "city": "Sudbury", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Elm Street", "street_number": "144", "postal_code": "P3C 1T7"}
{"name": "Black, Shoemaker, Robinson & Donaldson Limited (a division of J.D. Barnes Limited)", "phone": "519-822-4031", "city": "Guelph", "province": "ON", "country": "CANADA", "unit_number": "101", "street_name": "Woodlawn Rd. W.,", "street_number": "257", "postal_code": "N1H 8J1"}
{"name": "B.A. Jacobs Surveying Ltd.", "phone": "905-521-1535", "city": "Hamilton", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "Jackson Street East, Suite 102", "street_number": "152", "postal_code": "L8N 1L3"}
{"name": "Avanti Surveying Inc.", "phone": "416-231-1174", "city": "Toronto", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "North Queen Street, Suite 102", "street_number": "310", "postal_code": "M9C 5K4"}
{"name": "Ashenhurst Nouwens & Associates Inc.", "phone": "905-529-6316", "city": "Hamilton", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "King William Street, Suite 204", "street_number": "225", "postal_code": "L8R 1B1"}
{"name": "Arpentages Schultz Barrette Surveying", "phone": "613-632-7611", "city": "Hawkesbury", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "One Main Str. East, #", "street_number": "510", "postal_code": "K6A 1A1"}
{"name": "Arpentage Dutrisac Surveying Inc.", "phone": "613-446-7101", "city": "Rockland", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "- 2884, rue Chamberland Street", "street_number": "3", "postal_code": "K4K 1M6"}
{"name": "Archibald, Gray & McKay Ltd.", "phone": "519-685-5300", "city": "London", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "White Oak Road", "street_number": "3514", "postal_code": "N6E 2Z9"}
{"name": "Annis O'Sullivan Vollebekk Ltd. (Kemptville)", "phone": "613-258-1717", "city": "Kemptville", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "POB , 136 Prescott Street", "street_number": "1340", "postal_code": "K0G 1J0"}
{"name": "Annis O'Sullivan Vollebekk Ltd.", "phone": "613-727-0850", "city": "Nepean", "province": "ON", "country": "CANADA", "unit_number": "", "street_name": "- 14 Concourse Gate", "street_number": "500", "postal_code": "K0A 1W0"}
{"name": "Callon Dietz Incorporated Ontario Land Surveyors", "phone": "519-673-0220", "city": "London", "province": "ON", "country": "CANADA", "unit_number": "# 1", "street_name": "Adelaide Str. N.,", "street_number": "41", "postal_code": "P1A 4K3"}
